// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"file_system_worker"
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  void cancelUfsFile(i64 sessionId, i64 tempUfsFileId, CancelUfsFileTOptions options)")
	fmt.Fprintln(os.Stderr, "  void closeUfsFile(i64 sessionId, i64 tempUfsFileId, CloseUfsFileTOptions options)")
	fmt.Fprintln(os.Stderr, "  i64 completeUfsFile(i64 sessionId, i64 tempUfsFileId, CompleteUfsFileTOptions options)")
	fmt.Fprintln(os.Stderr, "  i64 createUfsFile(i64 sessionId, string ufsPath, CreateUfsFileTOptions options)")
	fmt.Fprintln(os.Stderr, "  i64 openUfsFile(i64 sessionId, string ufsPath, OpenUfsFileTOptions options)")
	fmt.Fprintln(os.Stderr, "  void sessionHeartbeat(i64 sessionId,  metrics)")
	fmt.Fprintln(os.Stderr, "  i64 getServiceVersion()")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := file_system_worker.NewFileSystemWorkerClientServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "cancelUfsFile":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "CancelUfsFile requires 3 args")
			flag.Usage()
		}
		argvalue0, err14 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err14 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err15 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err15 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		arg16 := flag.Arg(3)
		mbTrans17 := thrift.NewTMemoryBufferLen(len(arg16))
		defer mbTrans17.Close()
		_, err18 := mbTrans17.WriteString(arg16)
		if err18 != nil {
			Usage()
			return
		}
		factory19 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt20 := factory19.GetProtocol(mbTrans17)
		argvalue2 := file_system_worker.NewCancelUfsFileTOptions()
		err21 := argvalue2.Read(jsProt20)
		if err21 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.CancelUfsFile(value0, value1, value2))
		fmt.Print("\n")
		break
	case "closeUfsFile":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "CloseUfsFile requires 3 args")
			flag.Usage()
		}
		argvalue0, err22 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err22 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err23 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err23 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		arg24 := flag.Arg(3)
		mbTrans25 := thrift.NewTMemoryBufferLen(len(arg24))
		defer mbTrans25.Close()
		_, err26 := mbTrans25.WriteString(arg24)
		if err26 != nil {
			Usage()
			return
		}
		factory27 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt28 := factory27.GetProtocol(mbTrans25)
		argvalue2 := file_system_worker.NewCloseUfsFileTOptions()
		err29 := argvalue2.Read(jsProt28)
		if err29 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.CloseUfsFile(value0, value1, value2))
		fmt.Print("\n")
		break
	case "completeUfsFile":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "CompleteUfsFile requires 3 args")
			flag.Usage()
		}
		argvalue0, err30 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err30 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err31 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err31 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		arg32 := flag.Arg(3)
		mbTrans33 := thrift.NewTMemoryBufferLen(len(arg32))
		defer mbTrans33.Close()
		_, err34 := mbTrans33.WriteString(arg32)
		if err34 != nil {
			Usage()
			return
		}
		factory35 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt36 := factory35.GetProtocol(mbTrans33)
		argvalue2 := file_system_worker.NewCompleteUfsFileTOptions()
		err37 := argvalue2.Read(jsProt36)
		if err37 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.CompleteUfsFile(value0, value1, value2))
		fmt.Print("\n")
		break
	case "createUfsFile":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "CreateUfsFile requires 3 args")
			flag.Usage()
		}
		argvalue0, err38 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err38 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg40 := flag.Arg(3)
		mbTrans41 := thrift.NewTMemoryBufferLen(len(arg40))
		defer mbTrans41.Close()
		_, err42 := mbTrans41.WriteString(arg40)
		if err42 != nil {
			Usage()
			return
		}
		factory43 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt44 := factory43.GetProtocol(mbTrans41)
		argvalue2 := file_system_worker.NewCreateUfsFileTOptions()
		err45 := argvalue2.Read(jsProt44)
		if err45 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.CreateUfsFile(value0, value1, value2))
		fmt.Print("\n")
		break
	case "openUfsFile":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "OpenUfsFile requires 3 args")
			flag.Usage()
		}
		argvalue0, err46 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err46 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg48 := flag.Arg(3)
		mbTrans49 := thrift.NewTMemoryBufferLen(len(arg48))
		defer mbTrans49.Close()
		_, err50 := mbTrans49.WriteString(arg48)
		if err50 != nil {
			Usage()
			return
		}
		factory51 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt52 := factory51.GetProtocol(mbTrans49)
		argvalue2 := file_system_worker.NewOpenUfsFileTOptions()
		err53 := argvalue2.Read(jsProt52)
		if err53 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.OpenUfsFile(value0, value1, value2))
		fmt.Print("\n")
		break
	case "sessionHeartbeat":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "SessionHeartbeat requires 2 args")
			flag.Usage()
		}
		argvalue0, err54 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err54 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		arg55 := flag.Arg(2)
		mbTrans56 := thrift.NewTMemoryBufferLen(len(arg55))
		defer mbTrans56.Close()
		_, err57 := mbTrans56.WriteString(arg55)
		if err57 != nil {
			Usage()
			return
		}
		factory58 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt59 := factory58.GetProtocol(mbTrans56)
		containerStruct1 := file_system_worker.NewFileSystemWorkerClientServiceSessionHeartbeatArgs()
		err60 := containerStruct1.ReadField2(jsProt59)
		if err60 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.Metrics
		value1 := argvalue1
		fmt.Print(client.SessionHeartbeat(value0, value1))
		fmt.Print("\n")
		break
	case "getServiceVersion":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetServiceVersion requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetServiceVersion())
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
