// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package block_worker

import (
	"bytes"
	"common"
	"exception"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = common.GoUnusedProtection__
var _ = exception.GoUnusedProtection__
var GoUnusedProtection__ int

// Attributes:
//  - LockId
//  - BlockPath
type LockBlockResult_ struct {
	LockId    int64  `thrift:"lockId,1" json:"lockId"`
	BlockPath string `thrift:"blockPath,2" json:"blockPath"`
}

func NewLockBlockResult_() *LockBlockResult_ {
	return &LockBlockResult_{}
}

func (p *LockBlockResult_) GetLockId() int64 {
	return p.LockId
}

func (p *LockBlockResult_) GetBlockPath() string {
	return p.BlockPath
}
func (p *LockBlockResult_) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *LockBlockResult_) readField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.LockId = v
	}
	return nil
}

func (p *LockBlockResult_) readField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.BlockPath = v
	}
	return nil
}

func (p *LockBlockResult_) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("LockBlockResult"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *LockBlockResult_) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("lockId", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:lockId: ", p), err)
	}
	if err := oprot.WriteI64(int64(p.LockId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.lockId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:lockId: ", p), err)
	}
	return err
}

func (p *LockBlockResult_) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("blockPath", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:blockPath: ", p), err)
	}
	if err := oprot.WriteString(string(p.BlockPath)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.blockPath (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:blockPath: ", p), err)
	}
	return err
}

func (p *LockBlockResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LockBlockResult_(%+v)", *p)
}
